version: "2.1"

services:
 web:
  build: ./web
  expose:
   - "80"
  depends_on:
   - db
  tty:
    true
 db:
  build: ./db
  #image: microsoft/windowsservercore
  expose:
   - "1433"
  environment:
    - "ACCEPT_EULA='Y'"
  tty:
    true

networks:
  default:
    external:
      name: "nat"